# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SONAR_PROJECT_KEY: nodejs-app-sonar
  SONAR_HOST_URL: http://54.205.242.208:9000
  
jobs:
  build-test-deploy: 
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present 
  
    - name: install dependecies 
      run: npm install

    - name: sonarqube scan
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      run: |
        npm install -g sonar-scanner
        sonar-scanner \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
          -Dsonar.login=${{ env.SONAR_TOKEN }}
